# -*- coding: utf-8 -*-
"""
/***************************************************************************
 UHIModel
                                 A QGIS plugin
 Impact temperature with new land uses
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-07-10
        copyright            : (C) 2019 by Laurens Kik/MovaresNL
        email                : laurenskik@movares.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load UHIModel class from file UHIModel.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .uhimodel import UHIModel
    return UHIModel(iface)
