# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uhimodel_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UHIModelDialogBase(object):
    def setupUi(self, UHIModelDialogBase):
        UHIModelDialogBase.setObjectName("UHIModelDialogBase")
        UHIModelDialogBase.resize(461, 658)
        self.button_box = QtWidgets.QDialogButtonBox(UHIModelDialogBase)
        self.button_box.setGeometry(QtCore.QRect(290, 620, 161, 32))
        self.button_box.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.CB_temp = QtWidgets.QComboBox(UHIModelDialogBase)
        self.CB_temp.setGeometry(QtCore.QRect(20, 40, 361, 22))
        self.CB_temp.setObjectName("CB_temp")
        self.CB_landuse = QtWidgets.QComboBox(UHIModelDialogBase)
        self.CB_landuse.setGeometry(QtCore.QRect(20, 100, 361, 22))
        self.CB_landuse.setObjectName("CB_landuse")
        self.label = QtWidgets.QLabel(UHIModelDialogBase)
        self.label.setGeometry(QtCore.QRect(20, 20, 141, 16))
        self.label.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(UHIModelDialogBase)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 121, 16))
        self.label_2.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.Confirm_newlanduse = QtWidgets.QToolButton(UHIModelDialogBase)
        self.Confirm_newlanduse.setGeometry(QtCore.QRect(310, 270, 131, 21))
        font = QtGui.QFont()
        font.setFamily("MS  Dlg 2")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Confirm_newlanduse.setFont(font)
        self.Confirm_newlanduse.setStyleSheet("font: 75 11pt \"MS  Dlg 2\";\n"
"\n"
"")
        self.Confirm_newlanduse.setObjectName("Confirm_newlanduse")
        self.SB_UHII = QtWidgets.QSpinBox(UHIModelDialogBase)
        self.SB_UHII.setGeometry(QtCore.QRect(340, 210, 41, 22))
        self.SB_UHII.setObjectName("SB_UHII")
        self.label_3 = QtWidgets.QLabel(UHIModelDialogBase)
        self.label_3.setGeometry(QtCore.QRect(20, 210, 261, 16))
        self.label_3.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.TB_temp = QtWidgets.QToolButton(UHIModelDialogBase)
        self.TB_temp.setGeometry(QtCore.QRect(400, 40, 41, 21))
        self.TB_temp.setObjectName("TB_temp")
        self.TB_landuse = QtWidgets.QToolButton(UHIModelDialogBase)
        self.TB_landuse.setGeometry(QtCore.QRect(400, 100, 41, 21))
        self.TB_landuse.setObjectName("TB_landuse")
        self.label_4 = QtWidgets.QLabel(UHIModelDialogBase)
        self.label_4.setGeometry(QtCore.QRect(20, 140, 201, 16))
        self.label_4.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.LE_output = QtWidgets.QLineEdit(UHIModelDialogBase)
        self.LE_output.setGeometry(QtCore.QRect(20, 160, 361, 20))
        self.LE_output.setObjectName("LE_output")
        self.TB_output = QtWidgets.QToolButton(UHIModelDialogBase)
        self.TB_output.setGeometry(QtCore.QRect(400, 160, 41, 21))
        self.TB_output.setObjectName("TB_output")
        self.label_5 = QtWidgets.QLabel(UHIModelDialogBase)
        self.label_5.setGeometry(QtCore.QRect(20, 300, 181, 21))
        self.label_5.setStyleSheet("font: 11pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.TW_objects = QtWidgets.QTableWidget(UHIModelDialogBase)
        self.TW_objects.setGeometry(QtCore.QRect(10, 330, 441, 281))
        self.TW_objects.setRowCount(10)
        self.TW_objects.setColumnCount(4)
        self.TW_objects.setObjectName("TW_objects")
        item = QtWidgets.QTableWidgetItem()
        self.TW_objects.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_objects.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_objects.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TW_objects.setHorizontalHeaderItem(3, item)
        self.CB_newlanduselayer = QtWidgets.QComboBox(UHIModelDialogBase)
        self.CB_newlanduselayer.setGeometry(QtCore.QRect(20, 270, 131, 22))
        self.CB_newlanduselayer.setObjectName("CB_newlanduselayer")
        self.label_6 = QtWidgets.QLabel(UHIModelDialogBase)
        self.label_6.setGeometry(QtCore.QRect(20, 250, 251, 16))
        self.label_6.setObjectName("label_6")
        self.CB_newlanduse = QtWidgets.QComboBox(UHIModelDialogBase)
        self.CB_newlanduse.setGeometry(QtCore.QRect(170, 270, 121, 22))
        self.CB_newlanduse.setObjectName("CB_newlanduse")

        self.retranslateUi(UHIModelDialogBase)
        self.button_box.accepted.connect(UHIModelDialogBase.accept)
        self.button_box.rejected.connect(UHIModelDialogBase.reject)
        self.CB_temp.activated['QString'].connect(UHIModelDialogBase.show)
        QtCore.QMetaObject.connectSlotsByName(UHIModelDialogBase)

    def retranslateUi(self, UHIModelDialogBase):
        _translate = QtCore.QCoreApplication.translate
        UHIModelDialogBase.setWindowTitle(_translate("UHIModelDialogBase", "uhimodel"))
        self.label.setText(_translate("UHIModelDialogBase", "Temperature map:"))
        self.label_2.setText(_translate("UHIModelDialogBase", "Landuse map:"))
        self.Confirm_newlanduse.setText(_translate("UHIModelDialogBase", "Add New Land Use"))
        self.label_3.setText(_translate("UHIModelDialogBase", "Urban Heat Island Intensity (0-10°C): "))
        self.TB_temp.setText(_translate("UHIModelDialogBase", "..."))
        self.TB_landuse.setText(_translate("UHIModelDialogBase", "..."))
        self.label_4.setText(_translate("UHIModelDialogBase", "Select output file:"))
        self.TB_output.setText(_translate("UHIModelDialogBase", "..."))
        self.label_5.setText(_translate("UHIModelDialogBase", "Objects:"))
        item = self.TW_objects.horizontalHeaderItem(0)
        item.setText(_translate("UHIModelDialogBase", "Name"))
        item = self.TW_objects.horizontalHeaderItem(1)
        item.setText(_translate("UHIModelDialogBase", "Land use"))
        item = self.TW_objects.horizontalHeaderItem(2)
        item.setText(_translate("UHIModelDialogBase", "Temp change"))
        item = self.TW_objects.horizontalHeaderItem(3)
        item.setText(_translate("UHIModelDialogBase", "Color"))
        self.label_6.setText(_translate("UHIModelDialogBase", "Select layer to change land use: "))
